let en_strings = {
    // LoginWithEmailAndPassword
    email: 'E-mail',
    invalid_email: '電子郵件格式無效',
    wrong_password: '密碼錯誤',
    user_not_found: '帳號不存在，\n該帳戶有可能已被刪除',
    password: '密碼',
    login: '登入',
    dont_have_an_account: '未有用戶? ',
    register: '登記',
    forget_password: '忘記密碼',
    // AskAnExpert
    special_tag_1: "眼睛疼痛",
    special_tag_2: "視力模糊",
    special_tag_3: "分泌物",
    clear: "最新",
    clear_2: "發問",
    mini_question_title: "問。",
    question_card_title: "問。\n",

    post_question_label_1: "主題",
    post_question_label_2: "內容",
    post_question_checkbox: "我同意專家察看我的度數紀錄",
    post_question_roundbutton: "提交",
    post_question_button: "返回",
    post_question_farewell_title: "謝謝你的提問",
    post_question_farewell_message: "收集問題後，我們的專家會在一星期內回答你的，請耐心等候。如有緊急需要，請聯絡你的眼科醫生。",
    post_question_placeholder: "由於我們會在本程式內發佈專家回應，請注意不要留下個人資料",
    // Education
    dashboard1: " 你已完成了總進度{userTotalScore}%！ ",
    dashboard_button_title: "進度一覽",
    dashboard2: " 完成測驗以解鎖獎勵 ！",

    article_detail_button_1: "暫停錄音",
    article_detail_button_2: "播放錄音",

    eye_exercise_1: "按下「開始」\n讓眼睛離開手機屏幕\n跟隨聲音導航開始護眼運動",
    eye_exercise_2_1: "剛才放鬆了雙眼\n現在正式開始，\n總共",
    eye_exercise_2_2: "段的護眼運動",
    eye_exercise_3_1: "你已完成",
    eye_exercise_3_2: "段護眼運動\n想繼續嗎？",
    eye_exercise_button_1: "繼續",
    eye_exercise_button_2: "完前緩和",
    eye_exercise_4: "你已完成全部護眼運動\n只差讓眼睛緩和的步驟！",
    eye_exercise_5: "完前緩和",
    eye_exercise_6: "你已完成這次的護眼運動！",
    eye_exercise_7: "再來一組",

    severity1: "近視",
    renderDesc1: "暫無數據",
    renderDesc2: "度",
    renderDesc3: "你的左眼沒有",
    renderDesc4: "您有很淺的",
    renderDesc5: "距離淺",
    renderDesc6: "還有",
    renderDesc7: "度",
    renderDesc8: "您有淺",
    renderDesc9: "距離中度",
    renderDesc11: "度",
    renderDesc12: "您有中度",
    renderDesc13: "距離深",
    renderDesc14: "您有深",
    renderDesc15: "雙眼近視度數偏差超過300度，有形成弱視的風險! ",
    renderDesc16: "對比上次紀錄:",
    renderDesc17: "近視",
    renderDesc18: "遠視",
    renderDesc19: "散光",

    renderVA1: "右眼矯正視力：",
    renderVA2: "左眼矯正視力：",
    renderVA3: '不正常視力',
    renderVA4: '稍低於正常視力',
    renderVA5: '正常視力',

    updateProfile1: "更新資料完成",
    updateProfile2: "更新資料錯誤",
    updateProfile3: "姓",
    updateProfile4: "名",
    updateProfile5: "出生日期",
    updateProfile6: "電話號碼",
    updateProfile7: "職業",
    updateProfile8: "家族病史",
    updateProfile9: "已知眼疾",
    updateProfile10: "更新資料",

    familyList1: "選擇家庭成員",

    gender1: "男",
    gender2: "女",

    forgetPassword1: ' 請輸入電郵地址並重新設定 ',
    forgetPassword2: "電子郵箱地址 ： ",
    forgetPassword3: "發送",
    forgetPassword4: "請輸入有效的電郵地址",
    forgetPassword5: "找不到用戶",
    forgetPassword6: " 已發送重設密碼郵件！ ",
    forgetPassword7: " 請檢查電子郵箱 ",
    forgetPassword8: "返回",

    login1: "忘記密碼",
    login2: "電話號碼",
    login3: "提取驗證碼",
    login4: "未有用戶? ",
    login5: '登記',

};

export default en_strings;
