name: Deployment

on: 
  push:
    branches:
      - master
      - continuous-deployment
jobs:
  deployment:
    runs-on: macos-latest
    steps:
      - id: checkout-repo
        name: Read repository
        uses: actions/checkout@v2
      - id: setup-nodejs
        name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - id: run-build-scripts
        name: Build and export application
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          PLAYSTORE_SERVICE_ACCOUNT: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
        run: |
          echo $EXPO_ANDROID_KEYSTORE_PASSWORD > ./password.txt
          echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 -d > ./keystore.jks
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            password.txt
            keystore.jks

